### ISSUE TITLE
[Epic] Build a town

### ISSUE THREAD

**Issue by NextFire** [NextFire/yuru-new-horizons#2]
As a **player**, I want **to build a town** so that **I can enjoy the game**.

# User stories

### Game mechanics
- [x] Town model #5 
- [x] Building model #6 
- [x] Population model #15 
- [ ] Realistic constructions #26 
- [x] Robustness #50 
### User interface
- [x] Basic map visual interface #7 
- [x] Visualize town statistics #25 

### General
- [x] Construct #8 
- [x] Nice building menu #9 
- [ ] Demolish #10 
### Economy
- [x] Level up #12 
- [x] Visualize building statistics #13 
- [x] Generate ressources #14 

## Population management
- [x] Population growth #16 
- [x] Happiness level #17 
- [ ] Task assignment #18
