### ISSUE TITLE
1st Iteration Plan

### ISSUE THREAD

**Issue by NextFire** [NextFire/yuru-new-horizons#39]
This plan captures our work in the **1st Iteration**. This is a 2-week iteration starting April 5th, 2021. We will ship **April 17th, 2021**.

## Agenda
- **April 5th, 2021**: Start of the iteration
- **April 17th, 2021**: End of the iteration

### Town
- [x] Town model #5 @NextFire 
- [x] Building model #6 @NextFire 
- [ ] Basic map visual interface #7
- [x] Construct buildings #8 @NextFire 
- [x] Nice building menu #9 @NextFire 
- [ ] Visualize building statistics #13
- [x] Generate ressources #14 @NextFire 
### User experience
- [x] Nice main menu #19 @NextFire 
- [x] Game model #23 @NextFire 
- [x] Visualize town statistics #25 @NextFire 
- [ ] Save system #29

## Delivery
- [x] sources1.jar
- [x] manuel-utilisateur1.pdf
- [x] rapport1.pdf
- [ ] Personal reports
