### ISSUE TITLE
2nd Iteration Plan

### ISSUE THREAD

**Issue by NextFire** [NextFire/yuru-new-horizons#45]
This plan captures our work in the **2nd Iteration**. This is a 2-week iteration starting May 3rd, 2021. We will ship **May 15th, 2021**.

## Agenda
- **May 3rd, 2021**: Start of the iteration
- **May 15th, 2021**: End of the iteration

### Town
- [x] Basic map visual interface #7 (to be finished) @NextFire 
- [ ] Demolish buildings #10 @atribout 
- [ ] Level up buildings #12 @atribout 
- [ ] Visualize building statistics #13
- [x]  Robustness #50 @NextFire 
### User experience
- [x] Game mode selection #21 @DinoGurnari 
- [ ] Map selection #22 @DinoGurnari 
- [ ] Competitive mode #24 
- [x] Background music #27 @NextFire 
- [x] Save system #29 @DinoGurnari @NextFire 

## Delivery
- [x] sources2.jar
- [x] manuel-utilisateur2.pdf
- [x] rapport2.pdf
- [ ] Personal reports
