### ISSUE TITLE
3rd Iteration Plan

### ISSUE THREAD

**Issue by NextFire** [NextFire/yuru-new-horizons#57]
This plan captures our work in the **3rd Iteration**. This is a 2-week iteration starting May 17th, 2021. We will ship **May 29th, 2021**.

## Agenda
- **May 17th, 2021**: Start of the iteration
- **May 29th, 2021**: End of the iteration

### Town
- [ ] Demolish buildings #10 @atribout 
- [x] Level up buildings #12 @atribout @DinoGurnari 
- [x] Visualize building statistics #13 @DinoGurnari 
- [x] Population model #15 @NextFire 
- [x] Population growth #16 @NextFire 
- [x] Happiness level #17 @NextFire 
### User experience
- [ ] Map selection #22 @DinoGurnari 
- [x] Competitive mode #24 @DinoGurnari 
- [ ] Realistic constructions #26 
### Events
- [ ] Game achievements #30 

## Delivery
- [x] sources3.jar
- [x] manuel-utilisateur3.pdf
- [x] rapport3.pdf
- [ ] Personal reports
- [x] presentation3.pdf
- [x] repartition.txt
